export default {
  SET_ADD_POST_STATUS: "SET_ADD_POST_STATUS",
  ADD_POST_TO_ARRAY: "ADD_POST_TO_ARRAY",
  ADD_COMMENT_TO_POST: "ADD_COMMENT_TO_POST",
  REMOVE_ARTICLE: "REMOVE_ARTICLE",
  UPDATE_ARTICLE: "UPDATE_ARTICLE",
  REMOVE_COMMENT: "REMOVE_COMMENT",
  UPDATE_COMMENT: "UPDATE_COMMENT",
};
